name: pr-agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    paths:
      - 'db/migrations/*.sql'
  issue_comment:

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent_job:
    name: Run pr-agent script on PR with migration files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter files
        id: filter_files
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            migrations:
              - 'db/migrations/*.sql'
            repositories:
              - 'handler/*repository*.rb'

      - name: Setup Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.13'

      - name: Run pr-agent with custom prompt
        id: pr-agent-python
        if: steps.filter_files.outputs.migrations == 'true'  && steps.filter_files.outputs.repositories == 'true'
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          COMMAND: "/ask --config.model='gpt-4o-mini' \
 --response_language='ja_JP' \
 \"YOU HAVE TO WRITE RESULT IN JAPANESE. \
YOU HAVE TO CHECK THE MIGRATION FILES AND THE REPOSITORY FILE IN THIS PR, ESPECIALLY SQL QUERIES CONTAIONED DROP TABLE STATEMENT. \
If you find any DROP TABLE STATEMENT and at the same time THE SAME NAME TABLE IS USED on QUERY in REPOSITORY, then PRINT THIS 'FAIL: DROP TABLE と REPOSITORY のチェック' with h1 tag. \
If you find any DROP TABLE STATEMENT and at the same time THE SAME NAME TABLE DELETED on QUERY in REPOSITORY, then PRINT THIS 'FAIL: DROP TABLE と REPOSITORY のチェック' with h1 tag. \
If you find any DROP TABLE STATEMENT and at the same time THE SAME NAME TABLE IS NOT USED on QUERY in REPOSITORY, then PRINT THIS 'PASS'. \
If you find any DROP TABLE STATEMENT and at the same time THE SAME NAME TABLE DID NOT DELETE on QUERY in REPOSITORY, then PRINT THIS 'PASS'. \
YOU SHOULD NOT READ THE WHOLE FILES, JUST FOCUS ON THE SQL QUERIES. \
DO NOT WAISTE YOUR TOKENS TO READ THE WHOLE FILES.\""
        # Set Custom Prompt to checking Migration files
        run: |
          echo "Running pr-agent with custom prompt..."
          pip install pr-agent
          python3 bin/pr-agent.py


